"ci/cd":
  - .github/workflows/*
  - .github/labeler.yml

"documentation":
  - "**/*.md"

"w01":
  - "w01/**"
"w02":
  - "w02/**"
"w03":
  - "w03/**"
"w04":
  - "w04/**"
"w05":
  - "w05/**"
"w06":
  - "w06/**"
"w07":
  - "w07/**"
"w08":
  - "w08/**"
"w09":
  - "w09/**"
"w10":
  - "w10/**"
"w11":
  - "w11/**"
"w12":
  - "w12/**"